name: Build and test

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang]
        include:
          - os: windows-latest
            c_compiler: gcc
            cpp_compiler: g++
            generator: "\"MinGW Makefiles\""
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            generator: "\"Unix Makefiles\""
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
            generator: "\"Unix Makefiles\""
        exclude:
          - os: windows-latest
            c_compiler: clang
    env:
      CC: ${{ matrix.c_compiler }}
      CXX: ${{ matrix.cpp_compiler }}

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}
        -G ${{ matrix.generator }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}
